import type { ThemeConfig } from "antd";

export const config: ThemeConfig = {
  token: {
    colorBgContainerDisabled: "#F6F6F6",
    colorBgContainer: "#F5F6FA",
  },
  components: {
    Button: {
      borderRadius: 8,
      fontFamily: "NeueHaasDisplayLight",
      colorPrimaryBg: "#003EFF",
      colorPrimaryBgHover: "#003EFF",
      colorPrimaryActive: "#003EFF",
      controlHeightLG: 48,
      borderRadiusLG: 8,
      borderColorDisabled: "#F6F6F6",
      textHoverBg: "#fff",
      primaryColor: "#fff",
    },
    Input: {
      fontFamily: "NeueHaasDisplayMedium",
      inputFontSize: 14,
      inputFontSizeLG: 16,
      inputFontSizeSM: 12,
      activeBorderColor: "#D7D7D7",
      hoverBorderColor: "#D7D7D7",
      activeShadow: "none",
      activeBg: "none",
      controlHeightLG: 48,
      borderRadiusLG: 8,
    },
    InputNumber: {
      fontFamily: "NeueHaasDisplayMedium",
      inputFontSize: 14,
      inputFontSizeLG: 16,
      inputFontSizeSM: 12,
      activeBorderColor: "#D7D7D7",
      hoverBorderColor: "#D7D7D7",
      activeShadow: "none",
      activeBg: "none",
      controlHeightLG: 48,
      borderRadiusLG: 8,
    },
    Table: {
      fontFamily: "NeueHaasDisplayLight",
      cellFontSizeSM: 13,
      cellFontSizeMD: 13,
      cellFontSize: 13,
      headerBg: "#fff",
    },
    Typography: {
      fontFamily: "NeueHaasDisplayMedium",
      colorTextLabel: "#5D5D5D",
      titleMarginBottom: 0,
      fontSizeHeading1: 38,
      fontSizeHeading2: 28,
      fontSizeHeading3: 24,
      fontSizeHeading4: 20,
      fontSizeHeading5: 16,
      colorText: "#373B47",
    },
    Form: {
      labelColor: "#5D5D5D",
      labelFontSize: 14,
      labelHeight: 20,
      fontFamily: "NeueHaasDisplayMedium",
    },
    Menu: {
      fontFamily: "NeueHaasDisplayMedium",
      itemColor: "#697598",
      itemSelectedBg: "#FFF",
      itemSelectedColor: "#697598",
      itemBorderRadius: 100,
      itemHoverBg: "#697598",
      itemHoverColor: "#FFFFFF",
      iconSize: 14,
      fontSize: 14,
      activeBarBorderWidth: 0,
      subMenuItemBg: "#fff",
      subMenuItemBorderRadius: 0,
      itemActiveBg: "#FFF",
      itemHeight: 52,
    },
    Layout: {
      siderBg: "#ffffff",
      lightSiderBg: "#ffffff",
      headerBg: "#ffffff",
      bodyBg: "#F8F9FA",
      headerPadding: 45,
      headerHeight: 60,
    },
    Avatar: {
      containerSize: 35,
      containerSizeLG: 60,
      containerSizeSM: 24,
    },
    Select: {
      clearBg: "#fff",
      optionFontSize: 14,
      fontFamily: "NeueHaasDisplayMedium",
      optionSelectedColor: "#0765FF",
      colorBorder: "#E8E8E8",
      borderRadiusLG: 8,
      fontSize: 14,
      controlHeight: 32,
      controlHeightLG: 48,
      fontSizeIcon: 16,
      controlHeightSM: 24,
    },
    Card: {
      fontFamily: "NeueHaasDisplayMedium",
      fontSize: 14,
      fontSizeLG: 64,
      // colorTextHeading: "#808080",
      borderRadiusLG: 8,
      borderRadiusSM: 24,
      borderRadius: 24,
      // colorTextDescription: "#000",
    },
    Segmented: {
      itemSelectedBg: "rgba(19, 85, 255, 0.1)",
      itemSelectedColor: "#003EFF",
      itemColor: "#667085",
      itemHoverBg: "rgba(19, 85, 255, 0.1)",
      itemHoverColor: "#003EFF",
      trackBg: "#fff",
      trackPadding: 8,
      colorText: "",
      borderRadius: 6,
    },
    Badge: {
      colorBgContainer: "#003EFF",
      colorBorderBg: "#003EFF",
      colorText: "#fff",
    },
    Tag: {
      borderRadiusSM: 8,
      fontFamily: "NeueHaasDisplayMedium",
    },
    Collapse: {
      fontFamily: "NeueHaasDisplayMedium",
    },
    Switch: {
      trackHeightSM: 20,
      trackMinWidthSM: 36,
      handleSizeSM: 16,
      handleBg: "#fff",
    },
    Alert: {
      colorWarning: "rgba(255, 199, 0, 0.1)",
      colorWarningBg: "rgba(255, 199, 0, 0.1)",
      borderRadiusLG: 3,
      colorWarningBorder: "rgba(255, 199, 0, 0.1)",
      fontSizeIcon: 20,
      colorIcon: "#191919",
      colorIconHover: "#191919",
    },
    Divider: {
      colorSplit: "#EDEDED",
      lineWidth: 2,
    },
    List: {
      itemPadding: "12px 0",
      descriptionFontSize: 12,
      colorText: "#191919",
      fontFamily: "NeueHaasDisplayMedium",
    },
    Progress: {
      circleTextColor: "#1D2939",
      fontFamily: "NeueHaasDisplayMedium",
      circleTextFontSize: "12px",
    },
    Tabs: {
      inkBarColor: "#003EFF",
      itemActiveColor: "#003EFF",
      fontFamily: "NeueHaasDisplayMedium",
      itemColor: "#5D5D5D",
      itemHoverColor: "#003EFF",
    },
  },
};
